
target 'Kouclo-live' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'MJExtension'
pod 'LFLiveKit'
pod 'YYKit'
pod 'ijkplayer'
pod 'LookinServer'
end
