
target 'ShirwindLive' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'MJExtension'
pod 'LFLiveKit'
pod 'YYKit'
pod 'ijkplayer'
pod 'Masonry'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'FLAnimatedImage'
pod 'HyphenateChat'#环信SDK
pod 'LookinServer'#环信UI库
pod 'EaseIMKit'
end
